name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image for the backend
      - name: Build Docker image for backend
        run: |
          docker build -t serena08/rag-plagiat-backend ./backend
          
      - name: Push Docker image for backend
        run: |
          docker push serena08/rag-plagiat-backend

      # Build and push the Docker image for the frontend
      - name: Build Docker image for frontend
        run: |
          docker build -t serena08/rag-plagiat-frontend ./frontend

      - name: Push Docker image for frontend
        run: |
          docker push serena08/rag-plagiat-frontend
