name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main  # Déclenchement sur le push vers la branche "main"

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilisation d'une machine virtuelle Ubuntu pour l'exécution

    steps:
      # Étape 1 : Checkout du code source depuis le dépôt
      - name: Checkout code
        uses: actions/checkout@v2  # Cette étape permet de récupérer le code du dépôt

      # Étape 2 : Installer Docker Buildx pour un build multiplateforme (optionnel, utile si nécessaire)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Installer Docker Buildx pour les builds multiplateformes

      # Étape 3 : Connexion à Docker Hub avec tes identifiants secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Ton nom d'utilisateur Docker Hub depuis les secrets GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Ton mot de passe Docker Hub depuis les secrets GitHub

      # Étape 4 : Construire l'image Docker pour le backend
      - name: Build Docker image for backend
        run: |
          docker build -t serena08/rag-plagiat-backend ./backend  # Construction de l'image backend
        continue-on-error: false  # Le pipeline échoue si cette étape rencontre une erreur

      # Étape 5 : Pousser l'image Docker pour le backend vers Docker Hub
      - name: Push Docker image for backend
        run: |
          docker push serena08/rag-plagiat-backend  # Pousser l'image Docker du backend sur Docker Hub
        continue-on-error: false  # Le pipeline échoue si cette étape rencontre une erreur

      # Étape 6 : Construire l'image Docker pour le frontend
      - name: Build Docker image for frontend
        run: |
          docker build -t serena08/rag-plagiat-frontend ./frontend  # Construction de l'image frontend
        continue-on-error: false  # Le pipeline échoue si cette étape rencontre une erreur

      # Étape 7 : Pousser l'image Docker pour le frontend vers Docker Hub
      - name: Push Docker image for frontend
        run: |
          docker push serena08/rag-plagiat-frontend  # Pousser l'image Docker du frontend sur Docker Hub
        continue-on-error: false  # Le pipeline échoue si cette étape rencontre une erreur
